name: Push wiki

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git remote add wiki "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"
          git fetch wiki
          git push wiki HEAD:master
